[package]
name = "batch_worker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
influxdb2 = "0.3"
influxdb2-structmap = "0.2"
num-traits = "0.2"
chrono = "0.4"
tokio = { version = "1", features = ["full"] }
serde = "1.0"
serde_json = "1.0"
futures = "0.3.30"
